# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Publish python poetry package
        # You may pin to the exact commit or the version.
        # uses: JRubics/poetry-publish@07ac25f0c30f3f2fa98ef4f33b79dfdfc148810a
        uses: JRubics/poetry-publish@v1.3
        with:
          # The version of python to install
          python_version: 3.8
          # The version of poetry to install
          poetry_version: 1.0.10
          # API token to authenticate when uploading package to PyPI (https://pypi.org/manage/account/)
          pypi_token: ${{ secrets.PIPY_TOKEN }}
